# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#  app.google_cloud_storage.service:
#      class: \Google_Service_Storage
#      factory: [App\Factory\GoogleCloudStorageServiceFactory
#      factory_method: 'createService'
#      arguments:
#          -