acteur_socials:
    type:     rest
    resource: DocDepot\ApiBundle\Controller\ASController
relation_confiances:
    type:     rest
    resource: DocDepot\ApiBundle\Controller\RelAsController
    parent: acteur_socials
